services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    env_file:
      - apps/gateway/.env.local
    environment:
      - REDIS_URL=redis://redis:6379
      - PHYSICAL_HOSTNAME=${HOSTNAME}
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - apps/worker/.env.local
    environment:
      - REDIS_URL=redis://redis:6379
      - PHYSICAL_HOSTNAME=${HOSTNAME}
    depends_on:
      - redis
    restart: unless-stopped
